-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_ClassicEnrollmentForm" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "status" TEXT NOT NULL DEFAULT 'brouillon',
    "registrationDate" TEXT,
    "schoolLevel" TEXT,
    "programId" TEXT,
    "previousSchool" TEXT,
    "adminCode" TEXT,
    "academicYearId" TEXT,
    "lastName" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "birthPlaceCity" TEXT,
    "birthPlaceDept" TEXT,
    "birthDate" TEXT,
    "sex" TEXT,
    "bloodType" TEXT,
    "livesWith" TEXT,
    "religion" TEXT,
    "addressNumber" TEXT,
    "addressStreet" TEXT,
    "addressCity" TEXT,
    "addressPostalCode" TEXT,
    "addressZone" TEXT,
    "photoUrl" TEXT,
    "familyStatus" TEXT,
    "fatherName" TEXT,
    "fatherProfession" TEXT,
    "fatherOccupation" TEXT,
    "fatherEmail" TEXT,
    "fatherPhone" TEXT,
    "fatherNif" TEXT,
    "fatherCin" TEXT,
    "motherName" TEXT,
    "motherProfession" TEXT,
    "motherOccupation" TEXT,
    "motherEmail" TEXT,
    "motherPhone" TEXT,
    "motherNif" TEXT,
    "motherCin" TEXT,
    "guardianName" TEXT,
    "guardianProfession" TEXT,
    "guardianOccupation" TEXT,
    "guardianEmail" TEXT,
    "guardianPhone" TEXT,
    "guardianNif" TEXT,
    "guardianCin" TEXT,
    "vaccinesUpToDate" BOOLEAN,
    "longTermMedication" BOOLEAN,
    "medicationDetails" TEXT,
    "siblings" TEXT NOT NULL DEFAULT '[]',
    "declarationAccepted" BOOLEAN NOT NULL DEFAULT false,
    "declarationDate" DATETIME,
    "studentUserId" INTEGER,
    "admissionSubmissionId" TEXT,
    "createdById" INTEGER,
    "updatedById" INTEGER,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ClassicEnrollmentForm_programId_fkey" FOREIGN KEY ("programId") REFERENCES "Program" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "ClassicEnrollmentForm_academicYearId_fkey" FOREIGN KEY ("academicYearId") REFERENCES "AcademicYear" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "ClassicEnrollmentForm_studentUserId_fkey" FOREIGN KEY ("studentUserId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "ClassicEnrollmentForm_admissionSubmissionId_fkey" FOREIGN KEY ("admissionSubmissionId") REFERENCES "AdmissionSubmission" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "ClassicEnrollmentForm_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "ClassicEnrollmentForm_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_ClassicEnrollmentForm" ("addressCity", "addressNumber", "addressPostalCode", "addressStreet", "addressZone", "adminCode", "admissionSubmissionId", "birthDate", "birthPlaceCity", "birthPlaceDept", "bloodType", "createdAt", "createdById", "declarationAccepted", "declarationDate", "familyStatus", "fatherCin", "fatherEmail", "fatherName", "fatherNif", "fatherOccupation", "fatherPhone", "fatherProfession", "firstName", "guardianCin", "guardianEmail", "guardianName", "guardianNif", "guardianOccupation", "guardianPhone", "guardianProfession", "id", "lastName", "livesWith", "longTermMedication", "medicationDetails", "motherCin", "motherEmail", "motherName", "motherNif", "motherOccupation", "motherPhone", "motherProfession", "photoUrl", "previousSchool", "programId", "registrationDate", "religion", "schoolLevel", "sex", "siblings", "status", "studentUserId", "updatedAt", "updatedById", "vaccinesUpToDate") SELECT "addressCity", "addressNumber", "addressPostalCode", "addressStreet", "addressZone", "adminCode", "admissionSubmissionId", "birthDate", "birthPlaceCity", "birthPlaceDept", "bloodType", "createdAt", "createdById", "declarationAccepted", "declarationDate", "familyStatus", "fatherCin", "fatherEmail", "fatherName", "fatherNif", "fatherOccupation", "fatherPhone", "fatherProfession", "firstName", "guardianCin", "guardianEmail", "guardianName", "guardianNif", "guardianOccupation", "guardianPhone", "guardianProfession", "id", "lastName", "livesWith", "longTermMedication", "medicationDetails", "motherCin", "motherEmail", "motherName", "motherNif", "motherOccupation", "motherPhone", "motherProfession", "photoUrl", "previousSchool", "programId", "registrationDate", "religion", "schoolLevel", "sex", "siblings", "status", "studentUserId", "updatedAt", "updatedById", "vaccinesUpToDate" FROM "ClassicEnrollmentForm";
DROP TABLE "ClassicEnrollmentForm";
ALTER TABLE "new_ClassicEnrollmentForm" RENAME TO "ClassicEnrollmentForm";
CREATE INDEX "ClassicEnrollmentForm_programId_idx" ON "ClassicEnrollmentForm"("programId");
CREATE INDEX "ClassicEnrollmentForm_status_idx" ON "ClassicEnrollmentForm"("status");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
