-- CreateTable
CREATE TABLE "ClassicEnrollmentForm" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "status" TEXT NOT NULL DEFAULT 'brouillon',
    "registrationDate" TEXT,
    "schoolLevel" TEXT,
    "programId" TEXT,
    "previousSchool" TEXT,
    "adminCode" TEXT,
    "lastName" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "birthPlaceCity" TEXT,
    "birthPlaceDept" TEXT,
    "birthDate" TEXT,
    "sex" TEXT,
    "bloodType" TEXT,
    "livesWith" TEXT,
    "religion" TEXT,
    "addressNumber" TEXT,
    "addressStreet" TEXT,
    "addressCity" TEXT,
    "addressPostalCode" TEXT,
    "addressZone" TEXT,
    "photoUrl" TEXT,
    "familyStatus" TEXT,
    "fatherName" TEXT,
    "fatherProfession" TEXT,
    "fatherOccupation" TEXT,
    "fatherEmail" TEXT,
    "fatherPhone" TEXT,
    "fatherNif" TEXT,
    "fatherCin" TEXT,
    "motherName" TEXT,
    "motherProfession" TEXT,
    "motherOccupation" TEXT,
    "motherEmail" TEXT,
    "motherPhone" TEXT,
    "motherNif" TEXT,
    "motherCin" TEXT,
    "guardianName" TEXT,
    "guardianProfession" TEXT,
    "guardianOccupation" TEXT,
    "guardianEmail" TEXT,
    "guardianPhone" TEXT,
    "guardianNif" TEXT,
    "guardianCin" TEXT,
    "vaccinesUpToDate" BOOLEAN,
    "longTermMedication" BOOLEAN,
    "medicationDetails" TEXT,
    "siblings" TEXT NOT NULL DEFAULT '[]',
    "declarationAccepted" BOOLEAN NOT NULL DEFAULT false,
    "declarationDate" DATETIME,
    "studentUserId" INTEGER,
    "admissionSubmissionId" TEXT,
    "createdById" INTEGER,
    "updatedById" INTEGER,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ClassicEnrollmentForm_programId_fkey" FOREIGN KEY ("programId") REFERENCES "Program" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "ClassicEnrollmentForm_studentUserId_fkey" FOREIGN KEY ("studentUserId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "ClassicEnrollmentForm_admissionSubmissionId_fkey" FOREIGN KEY ("admissionSubmissionId") REFERENCES "AdmissionSubmission" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "ClassicEnrollmentForm_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "ClassicEnrollmentForm_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateIndex
CREATE INDEX "ClassicEnrollmentForm_programId_idx" ON "ClassicEnrollmentForm"("programId");

-- CreateIndex
CREATE INDEX "ClassicEnrollmentForm_status_idx" ON "ClassicEnrollmentForm"("status");
